<a href="https://colab.research.google.com/github/LatiefDataVisionary/gamafest-dsc-ipb-2026/blob/main/EDA_Gamafest_DSC_IPB_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [4]:
test_df = pd.read_csv("https://raw.githubusercontent.com/LatiefDataVisionary/gamafest-dsc-ipb-2026/refs/heads/main/dataset/test.csv")
train_df = pd.read_csv("https://raw.githubusercontent.com/LatiefDataVisionary/gamafest-dsc-ipb-2026/refs/heads/main/dataset/train.csv")

In [5]:
train_df.head(10)

,Id,match_id,date,gender,team,opponent,is_home,neutral,tournament,venue_country,...,confederation_team,confederation_opp,population_team,population_opp,gdp_per_capita_team,gdp_per_capita_opp,altitude_venue,distance_travel_team,distance_travel_opp,temperature_venue
0,M000001_Scotland,M000001,1872-11-30,M,Scotland,England,1,0,Friendly,Scotland,...,UEFA,UEFA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,M000001_England,M000001,1872-11-30,M,England,Scotland,0,0,Friendly,Scotland,...,UEFA,UEFA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,M000002_England,M000002,1873-03-08,M,England,Scotland,1,0,Friendly,England,...,UEFA,UEFA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,M000002_Scotland,M000002,1873-03-08,M,Scotland,England,0,0,Friendly,England,...,UEFA,UEFA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,M000003_Scotland,M000003,1874-03-07,M,Scotland,England,1,0,Friendly,Scotland,...,UEFA,UEFA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,M000003_England,M000003,1874-03-07,M,England,Scotland,0,0,Friendly,Scotland,...,UEFA,UEFA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,M000004_England,M000004,1875-03-06,M,England,Scotland,1,0,Friendly,England,...,UEFA,UEFA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,M000004_Scotland,M000004,1875-03-06,M,Scotland,England,0,0,Friendly,England,...,UEFA,UEFA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,M000005_Scotland,M000005,1876-03-04,M,Scotland,England,1,0,Friendly,Scotland,...,UEFA,UEFA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,M000005_England,M000005,1876-03-04,M,England,Scotland,0,0,Friendly,Scotland,...,UEFA,UEFA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
test_df.head(10)

,Id,match_id,date,gender,team,opponent,is_home,neutral,tournament,venue_country,confederation_team,confederation_opp,population_team,population_opp,gdp_per_capita_team,gdp_per_capita_opp,altitude_venue,distance_travel_team,distance_travel_opp,temperature_venue
0,M034984_Seychelles,M034984,2011-08-06,M,Seychelles,Mauritius,1,0,Indian Ocean Island Games,Seychelles,CAF,CAF,92409.0,1283330.0,12189.095160,9197.026972,-9999.0,0.000000,1751.895724,25.790169
1,M034984_Mauritius,M034984,2011-08-06,M,Mauritius,Seychelles,0,0,Indian Ocean Island Games,Seychelles,CAF,CAF,1283330.0,92409.0,9197.026972,12189.095160,-9999.0,1751.895724,0.000000,25.790169
2,M034985_Comoros,M034985,2011-08-06,M,Comoros,Maldives,1,1,Indian Ocean Island Games,Seychelles,CAF,AFC,656024.0,361575.0,1447.945144,7291.465967,-9999.0,1517.010705,5483.117523,25.790169
3,M034985_Maldives,M034985,2011-08-06,M,Maldives,Comoros,0,1,Indian Ocean Island Games,Seychelles,AFC,CAF,361575.0,656024.0,7291.465967,1447.945144,-9999.0,5483.117523,1517.010705,25.790169
4,M034986_Réunion,M034986,2011-08-06,M,Réunion,Madagascar,1,1,Indian Ocean Island Games,Seychelles,Unknown,CAF,NaN,21731053.0,NaN,531.265432,-9999.0,NaN,NaN,25.790169
5,M034986_Madagascar,M034986,2011-08-06,M,Madagascar,Réunion,0,1,Indian Ocean Island Games,Seychelles,CAF,Unknown,21731053.0,NaN,531.265432,NaN,-9999.0,NaN,NaN,25.790169
6,M034987_El Salvador,M034987,2011-08-07,M,El Salvador,Venezuela,1,1,Friendly,United States,CONCACAF,CONMEBOL,6114034.0,28715022.0,3266.010978,NaN,153.0,2663.738053,4171.351077,22.129547
7,M034987_Venezuela,M034987,2011-08-07,M,Venezuela,El Salvador,0,1,Friendly,United States,CONMEBOL,CONCACAF,28715022.0,6114034.0,NaN,3266.010978,153.0,4171.351077,2663.738053,22.129547
8,M034988_Mayotte,M034988,2011-08-08,M,Mayotte,Réunion,1,1,Indian Ocean Island Games,Seychelles,Unknown,Unknown,211786.0,NaN,NaN,NaN,-9999.0,NaN,NaN,25.790169
9,M034988_Réunion,M034988,2011-08-08,M,Réunion,Mayotte,0,1,Indian Ocean Island Games,Seychelles,Unknown,Unknown,NaN,211786.0,NaN,NaN,-9999.0,NaN,NaN,25.790169

In [7]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78772 entries, 0 to 78771
Data columns (total 47 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Id                          78772 non-null  object
 1   match_id                    78772 non-null  object
 2   date                        78772 non-null  object
 3   gender                      78772 non-null  object
 4   team                        78772 non-null  object
 5   opponent                    78772 non-null  object
 6   is_home                     78772 non-null  int64
 7   neutral                     78772 non-null  int64
 8   tournament                  78772 non-null  object
 9   venue_country               78772 non-null  object
 10  team_goals                  78772 non-null  int64
 11  opp_goals                   78772 non-null  int64
 12  team_points_last5           78478 non-null  float64
 13  opp_points_last5            78596 non-null  float64
 14  points_last5_diff           78332 non-null  float64
 15  team_gd_last5               78478 non-null  float64
 16  opp_gd_last5                78596 non-null  float64
 17  gd_last5_diff               78332 non-null  float64
 18  h2h_points_last5            66796 non-null  float64
 19  h2h_gd_last5                66796 non-null  float64
 20  days_since_last_match_team  78478 non-null  float64
 21  days_since_last_match_opp   78596 non-null  float64
 22  team_points_last10          78478 non-null  float64
 23  opp_points_last10           78596 non-null  float64
 24  team_avg_goals_last5        78478 non-null  float64
 25  team_avg_conceded_last5     78478 non-null  float64
 26  opp_avg_goals_last5         78596 non-null  float64
 27  opp_avg_conceded_last5      78596 non-null  float64
 28  team_win_rate_last10        78478 non-null  float64
 29  opp_win_rate_last10         78596 non-null  float64
 30  elo_team                    78772 non-null  float64
 31  elo_opponent                78772 non-null  float64
 32  rank_team                   36826 non-null  float64
 33  rank_opponent               36826 non-null  float64
 34  rank_diff                   34870 non-null  float64
 35  rank_missing_team           78772 non-null  int64
 36  rank_missing_opp            78772 non-null  int64
 37  confederation_team          78772 non-null  object
 38  confederation_opp           78772 non-null  object
 39  population_team             63900 non-null  float64
 40  population_opp              63900 non-null  float64
 41  gdp_per_capita_team         52815 non-null  float64
 42  gdp_per_capita_opp          52815 non-null  float64
 43  altitude_venue              58218 non-null  float64
 44  distance_travel_team        48380 non-null  float64
 45  distance_travel_opp         48380 non-null  float64
 46  temperature_venue           61698 non-null  float64
dtypes: float64(31), int64(6), object(10)
memory usage: 28.2+ MB

In [8]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42422 entries, 0 to 42421
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Id                    42422 non-null  object
 1   match_id              42422 non-null  object
 2   date                  42422 non-null  object
 3   gender                42422 non-null  object
 4   team                  42422 non-null  object
 5   opponent              42422 non-null  object
 6   is_home               42422 non-null  int64
 7   neutral               42422 non-null  int64
 8   tournament            42422 non-null  object
 9   venue_country         42422 non-null  object
 10  confederation_team    42422 non-null  object
 11  confederation_opp     42422 non-null  object
 12  population_team       39050 non-null  float64
 13  population_opp        39050 non-null  float64
 14  gdp_per_capita_team   27758 non-null  float64
 15  gdp_per_capita_opp    27758 non-null  float64
 16  altitude_venue        31516 non-null  float64
 17  distance_travel_team  25447 non-null  float64
 18  distance_travel_opp   25447 non-null  float64
 19  temperature_venue     36828 non-null  float64
dtypes: float64(8), int64(2), object(10)
memory usage: 6.5+ MB

In [10]:
train_df.describe(include='all')

,Id,match_id,date,gender,team,opponent,is_home,neutral,tournament,venue_country,...,confederation_team,confederation_opp,population_team,population_opp,gdp_per_capita_team,gdp_per_capita_opp,altitude_venue,distance_travel_team,distance_travel_opp,temperature_venue
count,78772,78772,78772,78772,78772,78772,78772.000000,78772.000000,78772,78772,...,78772,78772,6.390000e+04,6.390000e+04,52815.000000,52815.000000,58218.000000,48380.000000,48380.000000,61698.000000
unique,78772,39386,14881,2,294,294,NaN,NaN,186,268,...,7,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,M034983_Mauritius,M034983,2008-03-26,M,Sweden,Sweden,NaN,NaN,Friendly,United States,...,UEFA,UEFA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,2,128,69966,1207,1207,NaN,NaN,28006,2132,...,26916,26916,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,0.500000,0.269030,NaN,NaN,...,NaN,NaN,3.253328e+07,3.253328e+07,9854.331528,9854.331528,158.222062,1938.851671,1938.851671,18.180117
std,NaN,NaN,NaN,NaN,NaN,NaN,0.500003,0.443458,NaN,NaN,...,NaN,NaN,8.332939e+07,8.332939e+07,15493.540286,15493.540286,1240.901854,3021.255139,3021.255139,7.802716
min,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,...,NaN,NaN,5.960000e+02,5.960000e+02,12.802812,12.802812,-9999.000000,0.000000,0.000000,-20.497587
25%,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,...,NaN,NaN,3.543776e+06,3.543776e+06,735.981909,735.981909,45.000000,0.000000,0.000000,12.501454
50%,NaN,NaN,NaN,NaN,NaN,NaN,0.500000,0.000000,NaN,NaN,...,NaN,NaN,9.820481e+06,9.820481e+06,2818.913920,2818.913920,117.000000,599.634551,599.634551,19.680511
75%,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,NaN,NaN,...,NaN,NaN,3.077462e+07,3.077462e+07,12126.939199,12126.939199,320.000000,2509.508681,2509.508681,24.441889
max,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,NaN,NaN,...,NaN,NaN,1.240614e+09,1.240614e+09,185785.725925,185785.725925,1877.500000,19783.072925,19783.072925,38.179592

In [11]:
test_df.describe(include='all')

,Id,match_id,date,gender,team,opponent,is_home,neutral,tournament,venue_country,confederation_team,confederation_opp,population_team,population_opp,gdp_per_capita_team,gdp_per_capita_opp,altitude_venue,distance_travel_team,distance_travel_opp,temperature_venue
count,42422,42422,42422,42422,42422,42422,42422.000000,42422.000000,42422,42422,42422,42422,3.905000e+04,3.905000e+04,27758.000000,27758.000000,31516.000000,25447.000000,25447.000000,36828.000000
unique,42422,21211,3135,2,315,315,NaN,NaN,167,227,7,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,M049215_Comoros,M049215,2012-02-29,M,United States,United States,NaN,NaN,Friendly,United States,UEFA,UEFA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,2,144,28464,522,522,NaN,NaN,10940,1840,14205,14205,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,0.500000,0.330206,NaN,NaN,NaN,NaN,4.076812e+07,4.076812e+07,19556.442407,19556.442407,199.407000,2250.259343,2250.259343,18.165796
std,NaN,NaN,NaN,NaN,NaN,NaN,0.500006,0.470293,NaN,NaN,NaN,NaN,1.169747e+08,1.169747e+08,24414.984733,24414.984733,1069.772463,3283.498229,3283.498229,8.434776
min,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,NaN,NaN,5.200000e+02,5.200000e+02,228.213589,228.213589,-9999.000000,0.000000,0.000000,-22.231203
25%,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,NaN,NaN,3.210847e+06,3.210847e+06,3116.297759,3116.297759,45.000000,0.000000,0.000000,12.164188
50%,NaN,NaN,NaN,NaN,NaN,NaN,0.500000,0.000000,NaN,NaN,NaN,NaN,1.052380e+07,1.052380e+07,8329.271313,8329.271313,133.000000,1016.550063,1016.550063,19.639935
75%,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,NaN,NaN,NaN,NaN,3.775781e+07,3.775781e+07,29206.076719,29206.076719,320.000000,3014.435770,3014.435770,24.905315
max,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,NaN,NaN,NaN,NaN,1.428628e+09,1.428628e+09,189432.370013,189432.370013,1877.500000,19783.072925,19783.072925,38.661620

In [12]:
train_df.isnull().sum()

Id                                0
match_id                          0
date                              0
gender                            0
team                              0
opponent                          0
is_home                           0
neutral                           0
tournament                        0
venue_country                     0
team_goals                        0
opp_goals                         0
team_points_last5               294
opp_points_last5                176
points_last5_diff               440
team_gd_last5                   294
opp_gd_last5                    176
gd_last5_diff                   440
h2h_points_last5              11976
h2h_gd_last5                  11976
days_since_last_match_team      294
days_since_last_match_opp       176
team_points_last10              294
opp_points_last10               176
team_avg_goals_last5            294
team_avg_conceded_last5         294
opp_avg_goals_last5             176
opp_avg_conceded_last5          176
team_win_rate_last10            294
opp_win_rate_last10             176
elo_team                          0
elo_opponent                      0
rank_team                     41946
rank_opponent                 41946
rank_diff                     43902
rank_missing_team                 0
rank_missing_opp                  0
confederation_team                0
confederation_opp                 0
population_team               14872
population_opp                14872
gdp_per_capita_team           25957
gdp_per_capita_opp            25957
altitude_venue                20554
distance_travel_team          30392
distance_travel_opp           30392
temperature_venue             17074
dtype: int64

In [13]:
test_df.isnull().sum()

Id                          0
match_id                    0
date                        0
gender                      0
team                        0
opponent                    0
is_home                     0
neutral                     0
tournament                  0
venue_country               0
confederation_team          0
confederation_opp           0
population_team          3372
population_opp           3372
gdp_per_capita_team     14664
gdp_per_capita_opp      14664
altitude_venue          10906
distance_travel_team    16975
distance_travel_opp     16975
temperature_venue        5594
dtype: int64

In [14]:
train_df.duplicated().sum()

np.int64(0)

In [15]:
test_df.duplicated().sum()

np.int64(0)

In [17]:
train_df.corr(numeric_only=True)

,is_home,neutral,team_goals,opp_goals,team_points_last5,opp_points_last5,points_last5_diff,team_gd_last5,opp_gd_last5,gd_last5_diff,...,rank_missing_team,rank_missing_opp,population_team,population_opp,gdp_per_capita_team,gdp_per_capita_opp,altitude_venue,distance_travel_team,distance_travel_opp,temperature_venue
is_home,1.000000e+00,6.020310e-16,0.181683,-0.181683,0.017408,-0.061536,0.057242,0.023229,-0.061772,0.060691,...,0.001221,-0.001221,0.033377,-0.033377,0.028326,-0.028326,-1.985619e-16,-0.412343,0.412343,1.817285e-16
neutral,6.020310e-16,1.000000e+00,0.032114,0.032114,0.001545,-0.008271,0.007185,-0.015088,-0.021087,0.004477,...,-0.036475,-0.036475,0.065883,0.065883,-0.014859,-0.014859,-1.529536e-03,0.355018,0.355018,1.317104e-01
team_goals,1.816825e-01,3.211359e-02,1.000000,-0.194728,0.131803,-0.286238,0.300410,0.158336,-0.344786,0.361488,...,0.034364,0.040312,0.048565,-0.037919,0.039784,-0.026107,-1.411152e-02,-0.086640,0.072980,1.132900e-02
opp_goals,-1.816825e-01,3.211359e-02,-0.194728,1.000000,-0.201483,0.247611,-0.323225,-0.253808,0.309233,-0.403657,...,0.040312,0.034364,-0.037919,0.048565,-0.026107,0.039784,-1.411152e-02,0.072980,-0.086640,1.132900e-02
team_points_last5,1.740846e-02,1.545393e-03,0.131803,-0.201483,1.000000,0.025624,0.697657,0.809275,0.024654,0.562866,...,-0.002968,-0.009779,0.103962,0.024563,0.072506,0.054691,1.097988e-02,0.045407,0.056146,-3.794025e-02
opp_points_last5,-6.153638e-02,-8.271397e-03,-0.286238,0.247611,0.025624,1.000000,-0.698320,0.025057,0.809468,-0.562180,...,-0.008134,-0.002476,0.011856,0.103796,0.034999,0.064056,1.030030e-02,0.063629,0.017315,-2.797521e-02
points_last5_diff,5.724216e-02,7.185295e-03,0.300410,-0.323225,0.697657,-0.698320,1.000000,0.561672,-0.562990,0.805920,...,0.003291,-0.005584,0.066556,-0.057377,0.027070,-0.006760,3.931256e-04,-0.013067,0.027770,-7.300220e-03
team_gd_last5,2.322921e-02,-1.508766e-02,0.158336,-0.253808,0.809275,0.025057,0.561672,1.000000,0.026290,0.698295,...,0.001058,-0.001503,0.094561,0.014446,0.072331,0.055739,1.178300e-02,0.036056,0.055122,-3.862640e-02
opp_gd_last5,-6.177227e-02,-2.108723e-02,-0.344786,0.309233,0.024654,0.809468,-0.562990,0.026290,1.000000,-0.697205,...,0.000414,-0.000192,0.002774,0.096043,0.037916,0.067530,1.221933e-02,0.059572,0.011013,-2.964915e-02
gd_last5_diff,6.069066e-02,4.477432e-03,0.361488,-0.403657,0.562866,-0.562180,0.805920,0.698295,-0.697205,1.000000,...,0.000592,-0.000534,0.066510,-0.059143,0.024392,-0.007771,-9.819664e-04,-0.017198,0.031454,-6.512746e-03
h2h_points_last5,1.761496e-02,-2.939057e-03,0.229930,-0.255581,0.269202,-0.210495,0.342205,0.268674,-0.211528,0.343147,...,0.004062,-0.008636,0.094091,-0.041702,0.049739,-0.012225,-3.288518e-03,-0.033617,-0.043238,-8.468746e-03
h2h_gd_last5,2.697515e-02,3.233449e-19,0.333771,-0.333771,0.256538,-0.299848,0.396950,0.301135,-0.348774,0.464245,...,0.006374,-0.006374,0.073968,-0.073968,0.043128,-0.043128,-9.744310e-19,0.002208,-0.002208,9.477943e-19
days_since_last_match_team,5.048919e-03,-2.161656e-02,0.003722,0.048247,-0.075606,-0.024177,-0.037269,-0.063552,-0.020800,-0.032363,...,0.091348,0.073605,-0.029288,-0.014005,-0.049122,-0.033372,-1.502108e-02,-0.033597,-0.009771,6.700253e-03
days_since_last_match_opp,1.457671e-01,-1.264689e-02,0.072800,-0.026734,-0.025349,-0.072212,0.032698,-0.023670,-0.068345,0.031421,...,0.055538,0.066991,-0.008798,-0.022500,-0.028395,-0.034542,-1.557952e-02,-0.070177,0.036933,1.906311e-02
team_points_last10,2.175301e-02,5.714646e-03,0.147409,-0.226890,0.808797,0.031938,0.556210,0.692308,0.020706,0.482010,...,-0.017660,-0.024319,0.130014,0.029065,0.092442,0.077132,1.561458e-02,0.075678,0.080385,-5.986559e-02
opp_points_last10,-4.786000e-02,1.121055e-03,-0.279083,0.215512,0.056638,0.808847,-0.538979,0.046849,0.691468,-0.462483,...,-0.023747,-0.017502,0.022028,0.129730,0.065801,0.088016,1.532654e-02,0.084746,0.058864,-5.377173e-02
team_avg_goals_last5,1.624121e-02,1.697956e-02,0.185359,-0.083097,0.641607,0.027130,0.440411,0.760294,0.031888,0.522422,...,0.067247,0.061879,0.091162,0.022559,0.073619,0.044222,-2.119766e-02,0.008495,0.030984,-3.389081e-02
team_avg_conceded_last5,-2.027758e-02,4.169090e-02,-0.071379,0.317644,-0.619893,-0.013811,-0.434124,-0.790255,-0.008689,-0.561019,...,0.066633,0.064761,-0.062650,-0.003383,-0.044895,-0.046725,-4.913322e-02,-0.046086,-0.054815,2.793372e-02
opp_avg_goals_last5,-4.862445e-02,1.690010e-02,-0.115418,0.401490,0.008629,0.638596,-0.453446,0.003397,0.765387,-0.546247,...,0.064070,0.066462,0.011226,0.091763,0.028086,0.069714,-2.012626e-02,0.031995,-0.009558,-2.186678e-02
opp_avg_conceded_last5,4.931848e-02,4.978456e-02,0.428901,-0.098760,-0.030749,-0.621478,0.423527,-0.037088,-0.787030,0.537591,...,0.063708,0.067667,0.004649,-0.063589,-0.034624,-0.040588,-4.605318e-02,-0.061025,-0.026286,2.539516e-02
team_win_rate_last10,2.098688e-02,1.620063e-02,0.155939,-0.186240,0.780805,0.024947,0.541422,0.659533,0.019476,0.459021,...,0.012680,0.002559,0.128710,0.028729,0.106786,0.086702,5.507088e-03,0.069634,0.074298,-6.114038e-02
opp_win_rate_last10,-4.751110e-02,1.250170e-02,-0.237130,0.235435,0.042124,0.780187,-0.530090,0.037309,0.659500,-0.445852,...,0.004480,0.014075,0.021258,0.128539,0.075995,0.102537,4.621976e-03,0.077411,0.052767,-5.467029e-02
elo_team,3.409173e-02,-1.089873e-02,0.163387,-0.282302,0.570672,0.040708,0.379760,0.540312,0.038302,0.360076,...,-0.094264,-0.107518,0.133237,0.021095,0.284587,0.232432,2.253315e-02,0.123306,0.134395,-2.402738e-01
elo_opponent,-3.414360e-02,-1.663564e-02,-0.280602,0.165765,0.115727,0.570529,-0.326305,0.110918,0.536272,-0.304967,...,-0.105821,-0.092547,0.020650,0.132984,0.229406,0.281659,2.284862e-02,0.132087,0.120963,-2.386182e-01
rank_team,-1.666099e-02,4.971164e-02,-0.108679,0.237578,-0.434889,-0.070253,-0.264128,-0.417925,-0.068268,-0.253386,...,NaN,0.051293,-0.035106,0.007967,-0.175340,-0.198373,-5.749639e-02,-0.118937,-0.114758,2.926649e-01
rank_opponent,1.666099e-02,4.971164e-02,0.237578,-0.108679,-0.130320,-0.424965,0.212800,-0.131375,-0.406133,0.196515,...,0.051293,NaN,0.007967,-0.035106,-0.198373,-0.175340,-5.749639e-02,-0.114758,-0.118937,2.926649e-01
rank_diff,4.907761e-02,-2.810882e-19,0.365901,-0.365901,0.308393,-0.361934,0.486236,0.289652,-0.346733,0.463475,...,NaN,NaN,0.069936,-0.069936,-0.010915,0.010915,-4.345184e-19,-0.004236,0.004236,-3.165130e-19
rank_missing_team,1.221290e-03,-3.647460e-02,0.034364,0.040312,-0.002968,-0.008134,0.003291,0.001058,0.000414,0.000592,...,1.000000,0.900254,0.006524,-0.046891,-0.228763,-0.256432,2.667769e-03,-0.053632,-0.045680,5.956385e-04
rank_missing_opp,-1.221290e-03,-3.647460e-02,0.040312,0.034364,-0.009779,-0.002476,-0.005584,-0.001503,-0.000192,-0.000534,...,0.900254,1.000000,-0.046891,0.006524,-0.256432,-0.228763,2.667769e-03,-0.045680,-0.053632,5.956385e-04
population_team,3.337712e-02,6.588316e-02,0.048565,-0.037919,0.103962,0.011856,0.066556,0.094561,0.002774,0.066510,...,0.006524,-0.046891,1.000000,0.049062,0.008563,0.022662,2.605671e-02,0.084685,0.117581,8.687029e-03
population_opp,-3.337712e-02,6.588316e-02,-0.037919,0.048565,0.024563,0.103796,-0.057377,0.014446,0.096043,-0.059143,...,-0.046891,0.006524,0.049062,1.000000,0.022662,0.008563,2.605671e-02,0.117581,0.084685,8.687029e-03
gdp_per_capita_team,2.832569e-02,-1.485919e-02,0.039784,-0.026107,0.072506,0.034999,0.027070,0.072331,0.037916,0.024392,...,-0.228763,-0.256432,0.008563,0.022662,1.000000,0.398351,-1.528189e-03,0.042005,0.080973,-2.718544e-01
gdp_per_capita_opp,-2.832569e-02,-1.485919e-02,-0.026107,0.039784,0.054691,0.064056,-0.006760,0.055739,0.067530,-0.007771,...,-0.256432,-0.228763,0.022662,0.008563,0.398351,1.000000,-1.528189e-03,0.080973,0.042005,-2.718544e-01
altitude_venue,-1.985619e-16,-1.529536e-03,-0.014112,-0.014112,0.010980,0.010300,0.000393,0.011783,0.012219,-0.000982,...,0.002668,0.002668,0.026057,0.026057,-0.001528,-0.001528,1.000000e+00,-0.027841,-0.027841,-4.248639e-02
distance_travel_team,-4.123432e-01,3.550177e-01,-0.086640,0.072980,0.045407,0.063629,-0.013067,0.036056,0.059572,-0.017198,...,-0.053632,-0.045680,0.084685,0.117581,0.042005,0.080973,-2.784066e-02,1.000000,0.008382,2.645407e-02
distance_travel_opp,4.123432e-01,3.550177e-01,0.072980,-0.086640,0.056146,0.017315,0.027770,0.055122,0.011013,0.031454,...,-0.045680,-0.053632,0.117581,0.084685,0.080973,0.042005,-2.784066e-02,0.008382,1.000000,2.645407e-02
temperature_venue,1.817285e-16,1.317104e-01,0.011329,0.011329,-0.037940,-0.027975,-0.007300,-0.038626,-0.029649,-0.006513,...,0.000596,0.000596,0.008687,0.008687,-0.271854,-0.271854,-4.248639e-02,0.026454,0.026454,1.000000e+00

In [18]:
test_df.corr(numeric_only=True)

,is_home,neutral,population_team,population_opp,gdp_per_capita_team,gdp_per_capita_opp,altitude_venue,distance_travel_team,distance_travel_opp,temperature_venue
is_home,1.000000e+00,1.416263e-16,0.041117,-0.041117,0.028757,-0.028757,-1.961903e-16,-0.399260,0.399260,1.018127e-16
neutral,1.416263e-16,1.000000e+00,0.018464,0.018464,-0.079859,-0.079859,7.898559e-03,0.371075,0.371075,6.149681e-02
population_team,4.111694e-02,1.846433e-02,1.000000,0.029200,-0.040112,-0.031866,1.261125e-02,0.025249,0.103394,1.549663e-02
population_opp,-4.111694e-02,1.846433e-02,0.029200,1.000000,-0.031866,-0.040112,1.261125e-02,0.103394,0.025249,1.549663e-02
gdp_per_capita_team,2.875744e-02,-7.985876e-02,-0.040112,-0.031866,1.000000,0.252973,-4.567371e-02,0.039458,0.086557,-2.943706e-01
gdp_per_capita_opp,-2.875744e-02,-7.985876e-02,-0.031866,-0.040112,0.252973,1.000000,-4.567371e-02,0.086557,0.039458,-2.943706e-01
altitude_venue,-1.961903e-16,7.898559e-03,0.012611,0.012611,-0.045674,-0.045674,1.000000e+00,-0.028696,-0.028696,-6.841865e-02
distance_travel_team,-3.992605e-01,3.710754e-01,0.025249,0.103394,0.039458,0.086557,-2.869609e-02,1.000000,0.063043,-9.640371e-03
distance_travel_opp,3.992605e-01,3.710754e-01,0.103394,0.025249,0.086557,0.039458,-2.869609e-02,0.063043,1.000000,-9.640371e-03
temperature_venue,1.018127e-16,6.149681e-02,0.015497,0.015497,-0.294371,-0.294371,-6.841865e-02,-0.009640,-0.009640,1.000000e+00

In [19]:
train_df.corr(numeric_only=True).style.background_gradient(cmap='coolwarm')